version: "3"
services:

  crw_db:
    container_name: crw_db
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'master'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'test328'
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - crw_db:/var/lib/postgresql/data

  crw_db_migrate:
    image: migrate/migrate
    volumes:
      - ./crw/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:test328@crw_db:5432/master?sslmode=disable", "up" ]

  crw_redis:
    container_name : crw_redis
    image: redis:7.0.4
    restart: unless-stopped
    command: redis-server --requirepass "328test"

  app:
    container_name: crw_app
    build:
      context: .
      dockerfile: "Dockerfile"
    depends_on:
      - crw_db
      - crw_redis
    restart: unless-stopped
    environment:
      DB_URL: postgres://postgres:test328@crw_db:5432/master?sslmode=disable
      DB_HOST: crw_db
      DB_PORT: 5432
      DB_DATABASE: master
      DB_USERNAME: postgres
      DB_PASSWORD: test328
      REDIS_HOST: crw_redis
      REDIS_PASSWORD: 328test

volumes:
  crw_db:
